# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: Tejal Wakchoure's Personal Website.
meta_author: Tejal Wakchoure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings
color:
    text: '575757'
    heading: '000000'
    text_small_devices: '000000'
    
    accent: 'bc763d' # 'E82E2E'  '76296F'
    backgroundcol: 'ffe1cf' #'DAE6FF'
    backgroundcol_dark: 'bc763d' # 'dfae91' #'4B69AB'
    backgroundcol_light: 'FDF0E6' # 'e6ecf8'
    
    white: 'ffffff'
    gray: 'bfbfbf'

# Footer settings
footer:
  copyright: Tejal Wakchoure

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Credits content
credits: Tejal Wakchoure

# Build settings
markdown: kramdown
permalink: pretty
