# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: Hi! I'm Tejal. I'm a product manager at The Baltimore Banner and a graduate of Columbia's Lede Program for data journalism. Previously, I researched computational journalism at MIT and studied computer science at BITS Pilani. I write on technology, politics and pop culture, and speak three human and five beep-boop languages.
# description: Tejal Wakchoure's personal website - data and graphics journalist, newsroom product manager. Hi! I'm Tejal. I create products for the newsroom at The Baltimore Banner. I also tell stories using words and code as a data & graphics journalist trained at Columbia Journalism School's Lede Program for Data Journalism.

meta_author: Tejal Wakchoure
meta_author_twitter: tejaldehyde

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings - 404 page is done manually
color:
    backgroundcol: 'ffffff' #'C1DAFF' #'D4F5FF'
    backgroundcol_light: 'CDE1FF' #'dcf7ff' (preloader)
    backgroundcol_lightest: 'DCEAFF' #'e5f9ff' (preloader mobile + manually added on blog, change there if changed here)
    link: '9d00db' #'3C7CDD' #'2C82D6'
    link_dark:  '8209b1' #'0D5BCF' #'0755A4'
    text: '000' #'393939' #'575757'
    button: '484848'
    heading: '000000'
    white: 'ffffff'
    lightest_gray: 'ebebeb'
    light_gray: 'dcdcdc'
    gray: 'bfbfbf'
    # wave_text: '034558'

# font:
#     heading: "Poppins, Lato, 'Source Sans Pro', Helvetica, sans-serif"
#     text: "'Source Sans Pro', Helvetica, sans-serif"
#     brand: "'Raleway', 'Source Sans Pro', sans-serif"

# Footer settings
footer:
  copyright: Tejal Wakchoure

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Include content
# include: ['pages']
# project_structure:
#   - title: "iodine"
#     url: "/projects/iodine/"
#   - title: "broadway"
#     url: "/projects/broadway/"
# collections:
#   projects:
#     output: true  # Ensures each project gets its own page
#     permalink: /_projects/:name/  # Keeps projects in their own folders


collections:
  projects:
    output: true
    permalink: /:path/

# Credits content
credits: Tejal Wakchoure

# Build settings
markdown: kramdown
permalink: pretty
