# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: Tejal Wakchoure's personal website - writer, designer, and developer.
meta_author: Tejal Wakchoure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings - 404 page is done manually
color:
    backgroundcol: 'C1DAFF' #'D4F5FF'
    backgroundcol_light: 'CDE1FF' #'dcf7ff' (preloader)
    backgroundcol_lightest: 'DCEAFF' #'e5f9ff' (preloader mobile + manually added on blog, change there if changed here)
    link: '3C7CDD' #'2C82D6'
    link_dark: '0D5BCF' #'0755A4'
    text: '393939' #'575757'
    button: '484848'
    heading: '000000'
    white: 'ffffff'
    lightest_gray: 'ebebeb'
    gray: 'bfbfbf'
    # wave_text: '034558'

# Footer settings
footer:
  copyright: Tejal Wakchoure

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Include content
# include: ['pages']

collections:
  posts:
    output: true
    permalink: /:title/

# collections:
#   work_sections:
#     output: true
    # permalink: /:title/
    # permalink: /:categories/:title/

  # code:
  #   permalink: /code/:title/
  #   output: true
  # designs:
  #   permalink: /designs/:title/
  #   output: true

# Credits content
credits: Tejal Wakchoure

# Build settings
markdown: kramdown
permalink: pretty
