# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: Tejal Wakchoure's Personal Website. Hi! I'm Tejal. I'm a software developer, UI & UX designer, and cinema addict. I currently build code at Goldman Sachs and live in Mumbai, India. I studied computer science at BITS Pilani and pursued my undergraduate thesis with Andrew Lippman at the MIT Media Lab. I like to work on projects that are design-oriented and solve real-world human-computer interaction (HCI) problems. I like to work with people who value empathy-driven development. My research interests are interdisciplinary - I enjoy blending ideas from HCI and product design with literature, cinema, and economics. During my time at MIT, I worked on politics and computer vision for a grassroots-level analysis of news media. Here is an interview on my experience!
meta_author: Tejal Wakchoure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings
color:
    backgroundcol: 'D4F5FF' #'d1e7f4' #'ffe1cf'
    backgroundcol_light: 'dcf7ff' #'FDF0E6'
    backgroundcol_lightest: 'e5f9ff' #'FDF0E6'
    link: '2C82D6' #'bc763d'
    link_dark: '0755A4' #'97541e'
    text: '393939' #'575757'
    button: '484848'
    heading: '000000'
    white: 'ffffff'
    gray: 'bfbfbf'

# Footer settings
footer:
  copyright: Tejal Wakchoure

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Credits content
credits: Tejal Wakchoure

# Build settings
markdown: kramdown
permalink: pretty
