# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: "Personal Website"
skills_1: "Data Science"
skills_2: "UI/UX Design"
skills_3: "Social Network Analysis"
meta_author: Wakchoure Tejal

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings
color:
    text: '575757'
    text_light: 'ffffff'
    heading: '000000'
    accent: 'bc763d' # 'E82E2E'  '76296F'
    backgroundcol: 'ffe1cf' #'DAE6FF'
    backgroundcol_dark: 'bc763d' # 'dfae91' #'4B69AB'
    backgroundcol_light: 'FDF0E6' # 'e6ecf8'
    page_bkg: 'ffffff' # 'f2f2f2'
    gray: 'bfbfbf'
    gray_dark: '454545'


# Footer settings
footer:
  copyright: Tejal Wakchoure
  location: Location
  credits: Credits

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Credits content
credits:

# Build settings
markdown: kramdown
permalink: pretty
