# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: Tejal Wakchoure's Personal Website.
meta_author: Tejal Wakchoure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings
color:
    backgroundcol: 'D4F5FF' #'ffe1cf'
    backgroundcol_light: 'dcf7ff' #'FDF0E6'
    backgroundcol_lightest: 'e5f9ff' # 'f2fcff' #'FDF0E6'
    link: '2C82D6' #'bc763d'
    link_dark: '0755A4' #'97541e'
    text: '393939' #'575757'
    button: '484848'

    heading: '000000'
    white: 'ffffff'
    gray: 'bfbfbf'

# Footer settings
footer:
  copyright: Tejal Wakchoure

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Credits content
credits: Tejal Wakchoure

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
permalink: pretty
