# Site settings
title: Tejal Wakchoure
url: https://tejalwakchoure.github.io
description: Tejal Wakchoure's Personal Website.
meta_author: Tejal Wakchoure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership
bing_verify:

# Color settings
color:
    backgroundcol: 'D8EBF7' #'ffe1cf'
    accent: '2F2B6A' #'bc763d'
    backgroundcol_light: 'FDF0E6'
    accent_dark: '97541e'

    text: '575757'
    heading: '000000'
    white: 'ffffff'
    gray: 'bfbfbf'

# Footer settings
footer:
  copyright: Tejal Wakchoure

# Social networks usernames
social:
  - title: linkedin
    url: //linkedin.com/in/tejalw
  - title: github
    url: //github.com/tejalwakchoure

# Plugins
plugins:
  - jekyll-redirect-from

# Credits content
credits: Tejal Wakchoure

# Build settings
markdown: kramdown
permalink: pretty
