
backend:
 name: github
  repo: tejalwakchoure/tejalwakchoure.github.io
  branch: master
  site_domain: tejals-personal-website.netlify.app

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/assets/draft_upload" # Media files will be stored in the repo under images/uploads

collections:
  - name: "" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_work_sections/code/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "project-date", widget: "string"}
      # - {label: "Featured Image", name: "img", widget: "image"}
      # - {label: "Image Alt Text", name: "alt", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "description", widget: "markdown"}
      - {label: "Link Text", name: "link-type", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}

  # - name: "code" # Used in routes, e.g., /admin/collections/blog
  #   label: "Code" # Used in the UI
  #   folder: "_work_sections/code/_posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "project-date", widget: "string"}
  #     - {label: "Featured Image", name: "img", widget: "image"}
  #     - {label: "Image Alt Text", name: "alt", widget: "string"}
  #     - {label: "Summary", name: "summary", widget: "string"}
  #     # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "Body", name: "description", widget: "markdown"}
  #     - {label: "Link Text", name: "link-type", widget: "string"}
  #     - {label: "Link", name: "link", widget: "string"}

  # - name: "designs" # Used in routes, e.g., /admin/collections/blog
  #   label: "Designs" # Used in the UI
  #   folder: "_work_sections/designs/_posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "project-date", widget: "string"}
  #     - {label: "Featured Image", name: "img", widget: "image"}
  #     - {label: "Image Alt Text", name: "alt", widget: "string"}
  #     - {label: "The Problem", name: "summary", widget: "string"}
  #     # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "The Solution", name: "description", widget: "markdown"}
  #     - {label: "Link Text", name: "link-type", widget: "string"}
  #     - {label: "Link", name: "link", widget: "string"}

  # - name: "words" # Used in routes, e.g., /admin/collections/blog
  #   label: "Words" # Used in the UI
  #   folder: "_work_sections/designs/_posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "project-date", widget: "string"}
  #     - {label: "Featured Image", name: "img", widget: "image"}
  #     - {label: "Image Alt Text", name: "alt", widget: "string"}
  #     - {label: "The Problem", name: "summary", widget: "string"}
  #     # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "The Solution", name: "description", widget: "markdown"}
  #     - {label: "Link Text", name: "link-type", widget: "string"}
  #     - {label: "Link", name: "link", widget: "string"}


    
# collections:
#   - name: "posts"
#     label: "Post"
#     folder: "_posts"
#     filter:
#       field: language
#       value: en
#     fields:
#       - {label: "Language", name: "language"}